---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-workshop
  template:
    metadata:
      labels:
        app: cicd-workshop
    spec:
      containers:
      - name: cicd-workshop
        image: mrckurz/cicd-workshop-image:latest
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-workshop
spec:
  type: NodePort
  selector:
    app: cicd-workshop
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
